CREATE TABLE `IDEN_USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) BINARY NOT NULL COMMENT '用户登录名',
  `PASSWORD` VARCHAR(255) BINARY NOT NULL COMMENT '登录密码',
  `ENABLED` BIT(1) NOT NULL DEFAULT 1 COMMENT '可用? 0=false, 1=true',
  `ACCOUNT_NON_LOCKED` BIT(1) NOT NULL DEFAULT 1 COMMENT '账户没锁定? 0=false, 1=true',
  `ACCOUNT_NON_EXPIRED` BIT(1) NOT NULL DEFAULT 1 COMMENT '账户没过期?',
  `CREDENTIALS_NON_EXPIRED` BIT(1) NOT NULL DEFAULT 1 COMMENT '凭证没有过期?',
  `CREATE_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '创建者',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '创建时间',
  `LAST_MODIFIED_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '最后更新者',
  `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '最后更新时间',
  'VERSION' BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC))
COMMENT = '系统用户表';

CREATE TABLE `IDEN_ROLE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(150) BINARY NOT NULL COMMENT '角色编码',
  `DESCRIPTION` VARCHAR(255) BINARY NOT NULL COMMENT '角色描述',
  `ENABLED` BIT(1) NOT NULL DEFAULT 1 COMMENT '可用? 0=false, 1=true',
  `CREATE_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '创建者',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '创建时间',
  `LAST_MODIFIED_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '最后更新者',
  `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '最后更新时间',
  'VERSION' BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE_UNIQUE` (`CODE` ASC))
COMMENT = '系统用户表';

CREATE TABLE `IDEN_ACCESS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(150) BINARY NOT NULL COMMENT '访问编码',
  `DESCRIPTION` VARCHAR(255) BINARY NOT NULL COMMENT '访问描述',
  `URI` VARCHAR(150) BINARY NOT NULL COMMENT '访问URI',
  `METHOD` VARCHAR(150) BINARY NOT NULL DEFAULT 'ALL' COMMENT '访问方法, GET, POST, PUT, DELETE, ALL',
  `ENABLED` BIT(1) NOT NULL DEFAULT 1 COMMENT '可用? 0=false, 1=true',
  `CREATE_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '创建者',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '创建时间',
  `LAST_MODIFIED_BY` VARCHAR(45) NOT NULL DEFAULT 'UNKNOWN' COMMENT '最后更新者',
  `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT GETDATE() COMMENT '最后更新时间',
  'VERSION' BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE_UNIQUE` (`CODE` ASC))
COMMENT = '系统用户表';