server:
  port: 80
  servlet:
    context-path: /backend
  
spring:
  session:
    store-type: none
  security:
    user:
      name: maxadmin
      password: "000000"
      roles:
      - MAXADMIN
    
cheng:
  security:
    form:
      login-page: /sign-in
      login-processing-url: /security-auth
      index-page: /index
      logout-proccess-url: /logout
    session:
      max-sessions-prevents-login: false
      maximum-sessions: 1
      expired-url: /session/expired
      invalid-session-url: /session/invalid
    any-request-authenticated:
    - /index/**
  web:
    ajax-request-key: "X-Requested-With"
    ajax-request-value: "XMLHttpRequest"